env: requirements.txt unsupported version
currently, on `main` branch, there will be an error when installing from requirements.txt e.g.
```
BirdNET-Analyzer git:(main) pip install -r requirements.txt
Collecting librosa==0.9.2 (from -r requirements.txt (line 1))
  Downloading librosa-0.9.2-py3-none-any.whl.metadata (8.2 kB)
Collecting resampy (from -r requirements.txt (line 2))
  Downloading resampy-0.4.3-py3-none-any.whl.metadata (3.0 kB)
ERROR: Could not find a version that satisfies the requirement tensorflow==2.15.0 (from versions: 2.16.0rc0, 2.16.1, 2.16.2, 2.17.0rc0, 2.17.0rc1, 2.17.0, 2.17.1, 2.18.0rc0, 2.18.0rc1, 2.18.0rc2, 2.18.0)
ERROR: No matching distribution found for tensorflow==2.15.0
```

This is because TensorFlow 2.15.0 may be no longer available from PyPI without override.

Additionally, in this PR `matplotlib` was added in order to allow running of `birdnet_analyzer.gui` thus avoiding errors such as this:

```
BirdNET-Analyzer git:(main) ✗ python -m birdnet_analyzer.gui
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/ken/Documents/wk/BirdNET-Analyzer/birdnet_analyzer/gui/__main__.py", line 5, in <module>
    import birdnet_analyzer.gui.train as train
  File "/Users/ken/Documents/wk/BirdNET-Analyzer/birdnet_analyzer/gui/train.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
```