env: requirements.txt add matplotlib dependency for gui (#526)
In this PR `matplotlib` was added in order to allow running of `birdnet_analyzer.gui` thus avoiding errors such as this:

```
BirdNET-Analyzer git:(main) ✗ python -m birdnet_analyzer.gui
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/ken/Documents/wk/BirdNET-Analyzer/birdnet_analyzer/gui/__main__.py", line 5, in <module>
    import birdnet_analyzer.gui.train as train
  File "/Users/ken/Documents/wk/BirdNET-Analyzer/birdnet_analyzer/gui/train.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
```

This is a follow up to #525. Thank you, @Josef-Haupt for looking at and your feedback on that PR!